// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foo.proto

#ifndef PROTOBUF_foo_2eproto__INCLUDED
#define PROTOBUF_foo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_foo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsFooImpl();
void InitDefaultsFoo();
inline void InitDefaults() {
  InitDefaultsFoo();
}
}  // namespace protobuf_foo_2eproto
namespace prototest {
class Foo;
class FooDefaultTypeInternal;
extern FooDefaultTypeInternal _Foo_default_instance_;
}  // namespace prototest
namespace prototest {

// ===================================================================

class Foo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:prototest.Foo) */ {
 public:
  Foo();
  virtual ~Foo();

  Foo(const Foo& from);

  inline Foo& operator=(const Foo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Foo(Foo&& from) noexcept
    : Foo() {
    *this = ::std::move(from);
  }

  inline Foo& operator=(Foo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Foo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Foo* internal_default_instance() {
    return reinterpret_cast<const Foo*>(
               &_Foo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Foo* other);
  friend void swap(Foo& a, Foo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Foo* New() const PROTOBUF_FINAL { return New(NULL); }

  Foo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Foo& from);
  void MergeFrom(const Foo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Foo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string bar = 2;
  bool has_bar() const;
  void clear_bar();
  static const int kBarFieldNumber = 2;
  const ::std::string& bar() const;
  void set_bar(const ::std::string& value);
  #if LANG_CXX11
  void set_bar(::std::string&& value);
  #endif
  void set_bar(const char* value);
  void set_bar(const char* value, size_t size);
  ::std::string* mutable_bar();
  ::std::string* release_bar();
  void set_allocated_bar(::std::string* bar);

  // optional string baz = 3;
  bool has_baz() const;
  void clear_baz();
  static const int kBazFieldNumber = 3;
  const ::std::string& baz() const;
  void set_baz(const ::std::string& value);
  #if LANG_CXX11
  void set_baz(::std::string&& value);
  #endif
  void set_baz(const char* value);
  void set_baz(const char* value, size_t size);
  ::std::string* mutable_baz();
  ::std::string* release_baz();
  void set_allocated_baz(::std::string* baz);

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:prototest.Foo)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_bar();
  void clear_has_bar();
  void set_has_baz();
  void clear_has_baz();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr bar_;
  ::google::protobuf::internal::ArenaStringPtr baz_;
  ::google::protobuf::int32 id_;
  friend struct ::protobuf_foo_2eproto::TableStruct;
  friend void ::protobuf_foo_2eproto::InitDefaultsFooImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Foo

// required int32 id = 1;
inline bool Foo::has_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Foo::set_has_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Foo::clear_has_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Foo::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Foo::id() const {
  // @@protoc_insertion_point(field_get:prototest.Foo.id)
  return id_;
}
inline void Foo::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:prototest.Foo.id)
}

// required string bar = 2;
inline bool Foo::has_bar() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Foo::set_has_bar() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Foo::clear_has_bar() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Foo::clear_bar() {
  bar_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_bar();
}
inline const ::std::string& Foo::bar() const {
  // @@protoc_insertion_point(field_get:prototest.Foo.bar)
  return bar_.GetNoArena();
}
inline void Foo::set_bar(const ::std::string& value) {
  set_has_bar();
  bar_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:prototest.Foo.bar)
}
#if LANG_CXX11
inline void Foo::set_bar(::std::string&& value) {
  set_has_bar();
  bar_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:prototest.Foo.bar)
}
#endif
inline void Foo::set_bar(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_bar();
  bar_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:prototest.Foo.bar)
}
inline void Foo::set_bar(const char* value, size_t size) {
  set_has_bar();
  bar_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:prototest.Foo.bar)
}
inline ::std::string* Foo::mutable_bar() {
  set_has_bar();
  // @@protoc_insertion_point(field_mutable:prototest.Foo.bar)
  return bar_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Foo::release_bar() {
  // @@protoc_insertion_point(field_release:prototest.Foo.bar)
  clear_has_bar();
  return bar_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Foo::set_allocated_bar(::std::string* bar) {
  if (bar != NULL) {
    set_has_bar();
  } else {
    clear_has_bar();
  }
  bar_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bar);
  // @@protoc_insertion_point(field_set_allocated:prototest.Foo.bar)
}

// optional string baz = 3;
inline bool Foo::has_baz() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Foo::set_has_baz() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Foo::clear_has_baz() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Foo::clear_baz() {
  baz_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_baz();
}
inline const ::std::string& Foo::baz() const {
  // @@protoc_insertion_point(field_get:prototest.Foo.baz)
  return baz_.GetNoArena();
}
inline void Foo::set_baz(const ::std::string& value) {
  set_has_baz();
  baz_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:prototest.Foo.baz)
}
#if LANG_CXX11
inline void Foo::set_baz(::std::string&& value) {
  set_has_baz();
  baz_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:prototest.Foo.baz)
}
#endif
inline void Foo::set_baz(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_baz();
  baz_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:prototest.Foo.baz)
}
inline void Foo::set_baz(const char* value, size_t size) {
  set_has_baz();
  baz_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:prototest.Foo.baz)
}
inline ::std::string* Foo::mutable_baz() {
  set_has_baz();
  // @@protoc_insertion_point(field_mutable:prototest.Foo.baz)
  return baz_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Foo::release_baz() {
  // @@protoc_insertion_point(field_release:prototest.Foo.baz)
  clear_has_baz();
  return baz_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Foo::set_allocated_baz(::std::string* baz) {
  if (baz != NULL) {
    set_has_baz();
  } else {
    clear_has_baz();
  }
  baz_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), baz);
  // @@protoc_insertion_point(field_set_allocated:prototest.Foo.baz)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace prototest

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_foo_2eproto__INCLUDED
